projects:
  marketplaceAmplifyApi:
    schemaPath: amplify/backend/api/marketplaceAmplifyApi/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/lib/api.ts
        docsFilePath: src/graphql
        region: eu-west-2
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
