/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsExports = {
  aws_project_region: 'eu-west-2',
  aws_cognito_identity_pool_id:
    'eu-west-2:4a12f5de-5fa7-4e31-8c53-78a116edaf66',
  aws_cognito_region: 'eu-west-2',
  aws_user_pools_id: 'eu-west-2_xZFu9mKgb',
  aws_user_pools_web_client_id: '3dtchmgji2u2oj0feknv1ptmk3',
  oauth: {},
  aws_cognito_username_attributes: ['EMAIL'],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
}

export default awsExports
