'client-only'

import { Spectral } from 'next/font/google'
import { Header } from '@/app/components/header'
import { Providers } from '@/store/provider'
import { FooterFive } from '@/app/components/Footer'
import ScrollToTop from '@/app/components/scroll-to-top'

import 'yet-another-react-lightbox/styles.css'
import 'yet-another-react-lightbox/plugins/thumbnails.css'
import 'swiper/swiper-bundle.min.css'
import '../assets/scss/styles.scss'

const spectral = Spectral({
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// @ts-ignore
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={spectral.className}>
        <Providers>
          <Header aboutOverlay />
          {children}
          <FooterFive />
          <ScrollToTop />
        </Providers>
      </body>
    </html>
  )
}
