export const blogData = [
  {
    slug: 'unique-products',
    id: 'blog-09',
    title: 'Unique products that will impress your home in 2023.',
    mediumImage: '374x243.jpg',
    masonry: '366x238.jpg',
    largeImage: '854x491.jpg',
    extraLargeImage: '1146x745.jpg',
    altImage: 'Unique Products',
    date: '2023-11-27',
    author: 'Admin',
    categoryItem: 'deco',
    desc: 'Contrary to popular belief, Lorem Ipsum indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in…',
    category: ['all | <span>(09)</span>', 'deco | <span>(06)</span>'],
    tag: ['all', 'table'],
    blockquoteDesc:
      'Dalena dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore etyt dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi utino aliquip ex ea commodo consequat.',
    singleImgOne: '/images/rich-text/1-570x327.jpg',
    singleImgTwo: '/images/rich-text/2-570x327.jpg',
    singleImgAlt: 'Single Image',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'striped-rug',
    id: 'blog-08',
    title: 'Navy Blue & White Striped Area Rugs',
    mediumImage: '374x243.jpg',
    masonry: '366x494.jpg',
    largeImage: '854x491.jpg',
    extraLargeImage: '1146x745.jpg',
    altImage: 'Striped Rug',
    date: '2023-11-25',
    author: 'Admin',
    categoryItem: 'deco',
    desc: 'Contrary to popular belief, Lorem Ipsum indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in…',
    category: ['all | <span>(09)</span>', 'deco | <span>(06)</span>'],
    tag: ['all', 'rug'],
    blockquoteDesc:
      'Dalena dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore etyt dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi utino aliquip ex ea commodo consequat.',
    singleImgOne: '/images/rich-text/1-570x327.jpg',
    singleImgTwo: '/images/rich-text/2-570x327.jpg',
    singleImgAlt: 'Single Image',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'staircase',
    id: 'blog-07',
    title: 'Helendo White Coated Staircase Floating',
    mediumImage: '374x243.jpg',
    masonry: '366x376.jpg',
    largeImage: '854x491.jpg',
    extraLargeImage: '1146x745.jpg',
    altImage: 'Staircase',
    date: '2023-11-18',
    author: 'Admin',
    categoryItem: 'deco',
    desc: 'Contrary to popular belief, Lorem Ipsum indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in…',
    category: ['all | <span>(09)</span>', 'deco | <span>(06)</span>'],
    tag: ['all', 'chair'],
    blockquoteDesc:
      'Dalena dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore etyt dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi utino aliquip ex ea commodo consequat.',
    singleImgOne: '/images/rich-text/1-570x327.jpg',
    singleImgTwo: '/images/rich-text/2-570x327.jpg',
    singleImgAlt: 'Single Image',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'spatialize-decorations',
    id: 'blog-06',
    title: 'Spatialize with the decorations of the Helendo store.',
    mediumImage: '374x243.jpg',
    masonry: '366x376.jpg',
    largeImage: '854x491.jpg',
    extraLargeImage: '1146x745.jpg',
    altImage: 'Spatialize Decorations',
    date: '2023-11-11',
    author: 'Admin',
    categoryItem: 'wooden',
    desc: 'Contrary to popular belief, Lorem Ipsum indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in…',
    category: ['all | <span>(09)</span>', 'wooden | <span>(01)</span>'],
    tag: ['all', 'table'],
    blockquoteDesc:
      'Dalena dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore etyt dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi utino aliquip ex ea commodo consequat.',
    singleImgOne: '/images/rich-text/1-570x327.jpg',
    singleImgTwo: '/images/rich-text/2-570x327.jpg',
    singleImgAlt: 'Single Image',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'modern-furniture',
    id: 'blog-05',
    title: 'Decorate your home with the most modern furnishings.',
    mediumImage: '374x243.jpg',
    masonry: '366x257.jpg',
    largeImage: '854x491.jpg',
    extraLargeImage: '1146x745.jpg',
    altImage: 'Modern Furniture',
    date: '2023-11-10',
    author: 'Admin',
    categoryItem: 'deco',
    desc: 'Contrary to popular belief, Lorem Ipsum indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in…',
    category: ['all | <span>(09)</span>', 'deco | <span>(06)</span>'],
    tag: ['all', 'sofa'],
    blockquoteDesc:
      'Dalena dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore etyt dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi utino aliquip ex ea commodo consequat.',
    singleImgOne: '/images/rich-text/1-570x327.jpg',
    singleImgTwo: '/images/rich-text/2-570x327.jpg',
    singleImgAlt: 'Single Image',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'award-winning',
    id: 'blog-01',
    title: 'Intelligent, award-winning product of the designer Thomas in 2023.',
    mediumImage: '374x243.jpg',
    masonry: '366x423.jpg',
    largeImage: '854x491.jpg',
    extraLargeImage: '1146x745.jpg',
    altImage: 'Award Winning',
    date: '2023-10-23',
    author: 'Admin',
    categoryItem: 'furniture',
    desc: 'Contrary to popular belief, Lorem Ipsum indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in…',
    category: ['all | <span>(09)</span>', 'furniture | <span>(02)</span>'],
    tag: ['all', 'chair'],
    blockquoteDesc:
      'Dalena dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore etyt dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi utino aliquip ex ea commodo consequat.',
    singleImgOne: '/images/rich-text/1-570x327.jpg',
    singleImgTwo: '/images/rich-text/2-570x327.jpg',
    singleImgAlt: 'Single Image',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'interior-design',
    id: 'blog-04',
    title: 'Interior design is the art, the interior designer is the artist.',
    mediumImage: '374x243.jpg',
    masonry: '366x469.jpg',
    largeImage: '854x491.jpg',
    extraLargeImage: '1146x745.jpg',
    altImage: 'interior design',
    date: '2023-10-20',
    author: 'Admin',
    categoryItem: 'deco',
    desc: 'Contrary to popular belief, Lorem Ipsum indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in…',
    category: ['all | <span>(09)</span>', 'deco | <span>(06)</span>'],
    tag: ['all', 'chair'],
    blockquoteDesc:
      'Dalena dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore etyt dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi utino aliquip ex ea commodo consequat.',
    singleImgOne: '/images/rich-text/1-570x327.jpg',
    singleImgTwo: '/images/rich-text/2-570x327.jpg',
    singleImgAlt: 'Single Image',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'fitted-kitchen',
    id: 'blog-03',
    title: 'White Fitted Kitchen In Renovated Period Apartment',
    mediumImage: '374x243.jpg',
    masonry: '366x432.jpg',
    largeImage: '854x491.jpg',
    extraLargeImage: '1146x745.jpg',
    altImage: 'Fitted Kitchen',
    date: '2023-10-11',
    author: 'Admin',
    categoryItem: 'furniture',
    desc: 'Contrary to popular belief, Lorem Ipsum indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in…',
    category: ['all | <span>(09)</span>', 'furniture | <span>(02)</span>'],
    tag: ['all', 'chair'],
    blockquoteDesc:
      'Dalena dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore etyt dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi utino aliquip ex ea commodo consequat.',
    singleImgOne: '/images/rich-text/1-570x327.jpg',
    singleImgTwo: '/images/rich-text/2-570x327.jpg',
    singleImgAlt: 'Single Image',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'cotton-rug',
    id: 'blog-02',
    title: 'Helendo Wool & Cotton Rugs',
    mediumImage: '374x243.jpg',
    masonry: '366x257.jpg',
    largeImage: '854x491.jpg',
    extraLargeImage: '1146x745.jpg',
    altImage: 'Cotton Rugs',
    date: '2023-10-10',
    author: 'Admin',
    categoryItem: 'deco',
    desc: 'Contrary to popular belief, Lorem Ipsum indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in…',
    category: ['all | <span>(09)</span>', 'deco | <span>(06)</span>'],
    tag: ['all', 'rug'],
    blockquoteDesc:
      'Dalena dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore etyt dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi utino aliquip ex ea commodo consequat.',
    singleImgOne: '/images/rich-text/1-570x327.jpg',
    singleImgTwo: '/images/rich-text/2-570x327.jpg',
    singleImgAlt: 'Single Image',
    isFeatured: true,
    content: '',
  },
]
