export const featureProduct = [
  {
    id: 'featured-product-01',
    subTitle: 'Featured Product',
    title: 'Nancy Chair',
    excerpt:
      'When an unknown printer took a galley of type and scrambled it to make a type specimen book. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia.',
    image: '/images/featured-product/nancy-chair.png',
    altImage: 'Featured Product Image',
    path: '/products/nancy-chair',
    buttonText: 'Only $90',
  },
  {
    id: 'featured-product-02',
    subTitle: 'Featured Product',
    title: 'Table Wood Pine',
    excerpt:
      'Excepteur sint occaecat cupidatat non proident, sunt in culpaqui <br/> officia deserunt mollit anim id est laborum.',
    image: '/images/featured-product/table-wood-pine.png',
    altImage: 'Featured Product Image',
    path: '/products/table-wood-pine',
    buttonText: 'Only $50',
  },
  {
    id: 'featured-product-03',
    subTitle: 'Featured Product',
    title: 'Art Deco Home',
    excerpt:
      'Many desktop publishing packages and web page editors now use <br/> Lorem Ipsum as their default model text, and a search for.',
    image: '/images/featured-product/art-deco-home.png',
    altImage: 'Featured Product Image',
    path: '/products/art-deco-home',
    buttonText: 'Only $30',
  },
]

export const products = [
  {
    slug: 'animi-dolor-pariatur',
    id: 'product-12',
    title: 'Animi Dolor Pariatur',
    xsImage: '74x74.jpg',
    smImage: '300x300.jpg',
    mdImage: '585x585.jpg',
    altImage: 'Product Image',
    price: 10,
    desc: 'At vero accusamus et iusto odio dignissimos blanditiis praesentiums dolores molest.',
    sku: 500,
    category: 'accessory',
    availability: 'in-stock',
    size: 'large',
    color: 'green',
    tag: 'accessories',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'art-deco-home',
    id: 'product-07',
    title: 'Art Deco Home',
    xsImage: '74x74.jpg',
    smImage: '300x300.jpg',
    mdImage: '585x585.jpg',
    categoryBannerImg: '285x396.jpg',
    altImage: 'Product Image',
    price: 30,
    desc: 'At vero accusamus et iusto odio dignissimos blanditiis praesentiums dolores molest.',
    sku: 501,
    category: 'decoration',
    availability: 'in-stock',
    size: 'large',
    color: 'yellow',
    tag: 'deco',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'artificial-potted-plant',
    id: 'product-01',
    title: 'Artificial potted plant',
    xsImage: '74x74.jpg',
    smImage: '300x300.jpg',
    mdImage: '585x585.jpg',
    altImage: 'Product Image',
    price: 40,
    desc: 'At vero accusamus et iusto odio dignissimos blanditiis praesentiums dolores molest.',
    soldOutSticker: 'Out of Stock',
    sku: 502,
    category: 'decoration',
    availability: 'out-of-stock',
    size: 'medium',
    color: 'black',
    tag: 'deco',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'dark-green-jug',
    id: 'product-19',
    title: 'Dark Green Jug',
    xsImage: '74x74.jpg',
    smImage: '300x300.jpg',
    mdImage: '585x585.jpg',
    homeCollectionImg: '600x600.jpg',
    altImage: 'Product Image',
    price: 19,
    discountPrice: 17.1,
    desc: 'At vero accusamus et iusto odio dignissimos blanditiis praesentiums dolores molest.',
    bestSellerSticker: 'Sale',
    offerSticker: '-10%',
    sku: 518,
    category: 'decoration',
    availability: 'in-stock',
    size: 'large',
    color: 'green',
    tag: 'table',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'drinking-glasses',
    id: 'product-16',
    title: 'Drinking Glasses',
    xsImage: '74x74.jpg',
    smImage: '300x300.jpg',
    mdImage: '585x585.jpg',
    homeCollectionImg: '600x429.png',
    altImage: 'Product Image',
    price: 21,
    desc: 'At vero accusamus et iusto odio dignissimos blanditiis praesentiums dolores molest.',
    sku: 515,
    category: 'decoration',
    availability: 'in-stock',
    size: 'large',
    color: 'yellow',
    tag: 'table',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'helen-chair',
    id: 'product-13',
    title: 'Helen Chair',
    xsImage: '74x74.jpg',
    smImage: '300x300.jpg',
    mdImage: '585x585.jpg',
    categoryBannerImg: '568x389.jpg',
    altImage: 'Product Image',
    price: 92,
    discountPrice: 69.5,
    sku: 512,
    desc: 'At vero accusamus et iusto odio dignissimos blanditiis praesentiums dolores molest.',
    bestSellerSticker: 'Sale',
    offerSticker: '-25%',
    category: 'decoration',
    availability: 'in-stock',
    size: 'medium',
    color: 'yellow',
    tag: 'table',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'high-quality-glass-bottle',
    id: 'product-08',
    title: 'High Quality Glass Bottle',
    xsImage: '74x74.jpg',
    smImage: '300x300.jpg',
    mdImage: '585x585.jpg',
    altImage: 'Product Image',
    price: 35,
    discountPrice: 30.1,
    desc: 'At vero accusamus et iusto odio dignissimos blanditiis praesentiums dolores molest.',
    bestSellerSticker: 'Sale',
    offerSticker: '-14%',
    sku: 503,
    category: 'accessory',
    availability: 'in-stock',
    size: 'medium',
    color: 'black',
    tag: 'glass',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'living-room-bedroom-lights',
    id: 'product-09',
    title: 'Living Room & Bedroom Lights',
    xsImage: '74x74.jpg',
    smImage: '300x300.jpg',
    mdImage: '585x585.jpg',
    altImage: 'Product Image',
    price: 45,
    desc: 'At vero accusamus et iusto odio dignissimos blanditiis praesentiums dolores molest.',
    sku: 504,
    category: 'accessory',
    availability: 'in-stock',
    size: 'large',
    color: 'gray',
    tag: 'accessories',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'nancy-chair',
    id: 'product-05',
    title: 'Nancy Chair',
    xsImage: '74x74.jpg',
    smImage: '300x300.jpg',
    mdImage: '585x585.jpg',
    homeCollectionImg: '570x570.png',
    altImage: 'Product Image',
    price: 90,
    desc: 'At vero accusamus et iusto odio dignissimos blanditiis praesentiums dolores molest.',
    sku: 505,
    category: 'furniture',
    availability: 'in-stock',
    size: 'large',
    color: 'black',
    tag: 'chair',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'simple-chair',
    id: 'product-03',
    title: 'Simple Chair',
    xsImage: '74x74.jpg',
    smImage: '300x300.jpg',
    mdImage: '585x585.jpg',
    altImage: 'Product Image',
    price: 40,
    desc: 'At vero accusamus et iusto odio dignissimos blanditiis praesentiums dolores molest.',
    soldOutSticker: 'Out of Stock',
    sku: 506,
    category: 'furniture',
    availability: 'out-of-stock',
    size: 'large',
    color: 'yellow',
    tag: 'chair',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'smooth-disk',
    id: 'product-04',
    title: 'Smooth Disk',
    xsImage: '74x74.jpg',
    smImage: '300x300.jpg',
    mdImage: '585x585.jpg',
    altImage: 'Product Image',
    price: 46,
    desc: 'At vero accusamus et iusto odio dignissimos blanditiis praesentiums dolores molest.',
    sku: 507,
    category: 'accessory',
    availability: 'in-stock',
    size: 'medium',
    color: 'yellow',
    tag: 'accessories',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'table-black',
    id: 'product-18',
    title: 'Table Black',
    xsImage: '74x74.jpg',
    smImage: '300x300.jpg',
    mdImage: '585x585.jpg',
    homeCollectionImg: '655x500.png',
    altImage: 'Product Image',
    price: 67,
    desc: 'At vero accusamus et iusto odio dignissimos blanditiis praesentiums dolores molest.',
    sku: 517,
    category: 'decoration',
    availability: 'in-stock',
    size: 'medium',
    color: 'black',
    tag: 'table',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'table-wood-pine',
    id: 'product-06',
    title: 'Table Wood Pine',
    xsImage: '74x74.jpg',
    smImage: '300x300.jpg',
    mdImage: '585x585.jpg',
    categoryBannerImg: '580x213.jpg',
    altImage: 'Product Image',
    price: 50,
    desc: 'At vero accusamus et iusto odio dignissimos blanditiis praesentiums dolores molest.',
    sku: 508,
    category: 'furniture',
    availability: 'in-stock',
    size: 'large',
    color: 'red',
    tag: 'table',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'teapot-with-black-tea',
    id: 'product-02',
    title: 'Teapot with black tea',
    xsImage: '74x74.jpg',
    smImage: '300x300.jpg',
    mdImage: '585x585.jpg',
    altImage: 'Product Image',
    price: 25,
    desc: 'At vero accusamus et iusto odio dignissimos blanditiis praesentiums dolores molest.',
    sku: 509,
    category: 'accessory',
    availability: 'in-stock',
    size: 'small',
    color: 'black',
    tag: 'accessories',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'unique-decoration',
    id: 'product-11',
    title: 'Unique Decoration',
    xsImage: '74x74.jpg',
    smImage: '300x300.jpg',
    mdImage: '585x585.jpg',
    altImage: 'Product Image',
    price: 15,
    desc: 'At vero accusamus et iusto odio dignissimos blanditiis praesentiums dolores molest.',
    sku: 510,
    category: 'decoration',
    availability: 'in-stock',
    size: 'medium',
    color: 'red',
    tag: 'deco',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'vase-of-flowers',
    id: 'product-14',
    title: 'Vase Of Flowers',
    xsImage: '74x74.jpg',
    smImage: '300x300.jpg',
    mdImage: '585x585.jpg',
    categoryBannerImg: '285x396.jpg',
    altImage: 'Product Image',
    price: 77,
    desc: 'At vero accusamus et iusto odio dignissimos blanditiis praesentiums dolores molest.',
    sku: 513,
    category: 'decoration',
    availability: 'in-stock',
    size: 'medium',
    color: 'gray',
    tag: 'table',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'wood-eggs',
    id: 'product-15',
    title: 'Wood Eggs',
    xsImage: '74x74.jpg',
    smImage: '300x300.jpg',
    mdImage: '585x585.jpg',
    categoryBannerImg: '580x213.jpg',
    altImage: 'Product Image',
    price: 19,
    desc: 'At vero accusamus et iusto odio dignissimos blanditiis praesentiums dolores molest.',
    sku: 514,
    category: 'decoration',
    availability: 'in-stock',
    size: 'small',
    color: 'yellow',
    tag: 'table',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'wooden-box',
    id: 'product-10',
    title: 'Wooden Box',
    xsImage: '74x74.jpg',
    smImage: '300x300.jpg',
    mdImage: '585x585.jpg',
    homeCollectionImg: '585x585.jpg',
    altImage: 'Product Image',
    price: 27,
    desc: 'At vero accusamus et iusto odio dignissimos blanditiis praesentiums dolores molest.',
    sku: 511,
    category: 'accessory',
    availability: 'in-stock',
    size: 'small',
    color: 'red',
    tag: 'accessories',
    isFeatured: true,
    content: '',
  },
  {
    slug: 'wooden-cups',
    id: 'product-17',
    title: 'Wooden Cups',
    xsImage: '74x74.jpg',
    smImage: '300x300.jpg',
    mdImage: '585x585.jpg',
    homeCollectionImg: '400x450.png',
    altImage: 'Product Image',
    price: 29,
    desc: 'At vero accusamus et iusto odio dignissimos blanditiis praesentiums dolores molest.',
    sku: 516,
    category: 'decoration',
    availability: 'in-stock',
    size: 'large',
    color: 'green',
    tag: 'table',
    isFeatured: true,
    content: '',
  },
]

export const productFilter = [
  {
    slug: 'product-filter-info',
    categoryList: [
      {
        id: 'categoryList-01',
        categoryListTitle: 'accessory',
      },
      {
        id: 'categoryList-02',
        categoryListTitle: 'decoration',
      },
      {
        id: 'categoryList-03',
        categoryListTitle: 'furniture',
      },
    ],
    availabilityList: [
      {
        id: 'availabilityList-01',
        filterLabel: 'filter-availability-1',
        title: 'In stock (17)',
        name: 'In stock',
        checked: 'in-stock',
        key: 'in-stock',
        group: 'availability',
      },
      {
        id: 'availabilityList-02',
        filterLabel: 'filter-availability-2',
        title: 'Out of stock (2)',
        name: 'Out of stock',
        checked: 'out-of-stock',
        key: 'out-of-stock',
        group: 'availability',
      },
    ],
    productSizeList: [
      {
        id: 'size-01',
        filterLabel: 'lg-size',
        title: 'Large (9)',
        name: 'Large',
        checked: 'large',
        key: 'large',
        group: 'size',
      },
      {
        id: 'size-02',
        filterLabel: 'md-size',
        title: 'Medium (7)',
        name: 'Medium',
        checked: 'medium',
        key: 'medium',
        group: 'size',
      },
      {
        id: 'size-03',
        filterLabel: 'sm-size',
        title: 'Small (3)',
        name: 'Small',
        checked: 'small',
        key: 'small',
        group: 'size',
      },
    ],
    colorList: [
      {
        id: 'color-01',
        colorOption: 'black',
      },
      {
        id: 'color-02',
        colorOption: 'green',
      },
      {
        id: 'color-03',
        colorOption: 'gray',
      },
      {
        id: 'color-04',
        colorOption: 'red',
      },
      {
        id: 'color-05',
        colorOption: 'yellow',
      },
    ],
    tagList: [
      {
        id: 'tag-01',
        tagTitle: 'accessories',
        marginRight: 'mr-[10px]',
      },
      {
        id: 'tag-02',
        tagTitle: 'chair',
        marginRight: 'mr-[10px]',
      },
      {
        id: 'tag-03',
        tagTitle: 'glass',
        marginRight: 'mr-[10px]',
      },
      {
        id: 'tag-04',
        tagTitle: 'deco',
        marginRight: 'mr-[10px]',
      },
      {
        id: 'tag-05',
        tagTitle: 'table',
        marginRight: '',
      },
    ],
    content: '',
  },
]
